export type { ASTExpr, ASTColumn, ASTCommand, ASTOrderBy, ASTCase, ASTWhen, ASTCast, ASTExists, ASTSubquery, ASTInQuery, ASTSelect, ASTApply, ASTInsertCommand, ASTUpdateCommand, ASTDeleteCommand, ASTOnConflict, ASTOnConflictDoNothing, ASTOnConflictDoUpdate, ASTSetOperation, ASTWindow, ASTFrameSpec, ASTFrameBound, ASTWith, ASTCTEDef } from './ast.js'
export {
  serial,
  bigserial,
  text,
  varchar,
  char,
  integer,
  smallint,
  bigint,
  doublePrecision,
  real,
  numeric,
  boolean,
  uuid,
  timestamp,
  timestamptz,
  date,
  time,
  timetz,
  interval,
  json,
  bytea,
  table,
  tableAs,
  TableName,
  Columns,
  OriginalName,
  TableAs,
} from './schema.js'
export type { ColumnDef, TableDef, ColumnsConfig, InferSelect, InferInsert, Nullable } from './schema.js'
export {
  // Generic operator helpers
  op,
  unaryOp,
  // Comparison
  eq,
  ne,
  gt,
  gte,
  lt,
  lte,
  isDistinctFrom,
  isNotDistinctFrom,
  // Pattern matching
  like,
  notLike,
  ilike,
  notIlike,
  // Logical
  and,
  or,
  not,
  // Null checks
  isNull,
  isNotNull,
  // Boolean tests
  isTrue,
  isNotTrue,
  isFalse,
  isNotFalse,
  isUnknown,
  isNotUnknown,
  // IN / BETWEEN
  inList,
  notInList,
  between,
  notBetween,
  betweenSymmetric,
  notBetweenSymmetric,
  // Arithmetic
  add,
  sub,
  mul,
  div,
  mod,
  pow,
  neg,
  // String operators
  concat,
  // Bitwise operators
  bitAnd,
  bitOr,
  bitXor,
  bitNot,
  leftShift,
  rightShift,
  // JSON operators
  jsonGet,
  jsonGetText,
  jsonPath,
  jsonPathText,
  jsonContains,
  jsonContainedBy,
  jsonHasKey,
  jsonHasAnyKey,
  jsonHasAllKeys,
  // Array operators
  arrayOverlap,
  // CASE / CAST / EXISTS / Subqueries
  caseWhen,
  cast,
  subquery,
  exists,
  inSubquery,
  notInSubquery,
  // Aggregate functions
  count,
  sum,
  avg,
  min,
  max,
  stringAgg,
  arrayAgg,
  boolAnd,
  boolOr,
  jsonAgg,
  jsonObjectAgg,
  // Statistical aggregates
  variance,
  varSamp,
  varPop,
  stddev,
  stddevSamp,
  stddevPop,
  // Bitwise aggregates
  bitAndAgg,
  bitOrAgg,
  bitXorAgg,
  // EVERY
  every,
  // Aggregate FILTER
  filter,
  // Scalar functions
  fn,
  // Named scalar functions — String
  lower,
  upper,
  length,
  trim,
  ltrim,
  rtrim,
  substring,
  replace,
  concatWs,
  reverse,
  repeat,
  lpad,
  rpad,
  // Named scalar functions — Math
  abs,
  ceil,
  floor,
  round,
  trunc,
  sqrt,
  sign,
  random,
  greatest,
  least,
  // Named scalar functions — Null handling
  coalesce,
  nullif,
  // Named scalar functions — Date/time
  now,
  currentDate,
  currentTime,
  datePart,
  dateTrunc,
  toChar,
  // Named scalar functions — UUID
  genRandomUuid,
  // Window functions
  over,
  rowNumber,
  rank,
  denseRank,
  ntile,
  lag,
  lead,
  firstValue,
  lastValue,
  nthValue,
  // Frame bounds
  unboundedPreceding,
  unboundedFollowing,
  currentRow,
  preceding,
  following,
  // CTE
  withCTE,
  // Alias / Literal
  alias,
  literal,
} from './expressions.js'
export type { OverOptions } from './expressions.js'
export { quarry, asc, desc, QuarryDB, FromableBuilder, SelectBuilder, SetOperationBuilder, InsertBuilder, InsertSelectBuilder, UpdateBuilder, DeleteBuilder } from './builder.js'
export type { QuarrySession, QueryBuilder } from './builder.js'
