package io.github.edadma.petradb.jdbc

import io.github.edadma.petradb.{TableValue, Metadata}

import java.sql.{SQLFeatureNotSupportedException, SQLWarning, ResultSet, Connection}

abstract class AbstractStatement extends java.sql.Statement:

  protected def emptyRS: ResultSet =
    new PetraResultSet(TableValue(Vector.empty, Metadata(Vector.empty)))

  def getMaxFieldSize(): Int          = 0
  def setMaxFieldSize(max: Int): Unit = ()
  def getMaxRows(): Int               = 0
  def setMaxRows(max: Int): Unit      = ()
  def setEscapeProcessing(enable: Boolean): Unit = ()
  def getQueryTimeout(): Int               = 0
  def setQueryTimeout(seconds: Int): Unit  = ()
  def cancel(): Unit                       = ()
  def getWarnings(): SQLWarning            = null
  def clearWarnings(): Unit                = ()
  def setCursorName(name: String): Unit    = throw SQLFeatureNotSupportedException()
  def getMoreResults(): Boolean            = false
  def setFetchDirection(direction: Int): Unit = ()
  def getFetchDirection(): Int             = ResultSet.FETCH_FORWARD
  def setFetchSize(rows: Int): Unit        = ()
  def getFetchSize(): Int                  = 0
  def getResultSetConcurrency(): Int       = ResultSet.CONCUR_READ_ONLY
  def getResultSetType(): Int              = ResultSet.TYPE_FORWARD_ONLY
  def addBatch(sql: String): Unit          = throw SQLFeatureNotSupportedException()
  def clearBatch(): Unit                   = ()
  def executeBatch(): Array[Int]           = throw SQLFeatureNotSupportedException()
  def getMoreResults(current: Int): Boolean = false
  def getGeneratedKeys(): ResultSet        = emptyRS
  def executeUpdate(sql: String, autoGeneratedKeys: Int): Int    = executeUpdate(sql)
  def executeUpdate(sql: String, columnIndexes: Array[Int]): Int = executeUpdate(sql)
  def executeUpdate(sql: String, columnNames: Array[String]): Int = executeUpdate(sql)
  def execute(sql: String, autoGeneratedKeys: Int): Boolean      = execute(sql)
  def execute(sql: String, columnIndexes: Array[Int]): Boolean   = execute(sql)
  def execute(sql: String, columnNames: Array[String]): Boolean  = execute(sql)
  def getResultSetHoldability(): Int       = ResultSet.CLOSE_CURSORS_AT_COMMIT
  def setPoolable(poolable: Boolean): Unit = ()
  def isPoolable(): Boolean                = false
  def closeOnCompletion(): Unit            = ()
  def isCloseOnCompletion(): Boolean       = false
  def unwrap[T](iface: Class[T]): T       = throw java.sql.SQLException("not a wrapper")
  def isWrapperFor(iface: Class[?]): Boolean = false
